"""Seed MongoDB with coding questions only. HR/Manager/Technical questions are generated by the LLM based on resume + JD."""

import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
from app.config import settings

CODING_QUESTIONS = [
    # EASY
    {
        "round_type": "coding",
        "difficulty": "easy",
        "title": "Two Sum",
        "prompt": "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.",
        "description": "You may assume that each input would have exactly one solution, and you may not use the same element twice. You can return the answer in any order.",
        "examples": [
            {"input": "nums = [2,7,11,15], target = 9", "output": "[0,1]", "explanation": "nums[0] + nums[1] == 9"},
            {"input": "nums = [3,2,4], target = 6", "output": "[1,2]", "explanation": "nums[1] + nums[2] == 6"},
        ],
        "constraints": ["2 <= nums.length <= 10^4", "-10^9 <= nums[i] <= 10^9", "Only one valid answer exists."],
        "hints": ["Think about what complement you need for each number.", "A hash map can help you look up complements in O(1).", "Iterate once, checking if complement exists in the map."],
        "optimal_complexity": "O(n) time, O(n) space",
        "category": "hash_map",
    },
    {
        "round_type": "coding",
        "difficulty": "easy",
        "title": "Reverse Linked List",
        "prompt": "Given the head of a singly linked list, reverse the list, and return the reversed list.",
        "description": "Reverse a singly linked list iteratively or recursively.",
        "examples": [
            {"input": "head = [1,2,3,4,5]", "output": "[5,4,3,2,1]", "explanation": "The list is reversed."},
            {"input": "head = [1,2]", "output": "[2,1]", "explanation": "Simple two-node reversal."},
        ],
        "constraints": ["0 <= Number of nodes <= 5000", "-5000 <= Node.val <= 5000"],
        "hints": ["Keep track of the previous node as you traverse.", "You need three pointers: prev, current, next.", "At each step, reverse the current node's pointer."],
        "optimal_complexity": "O(n) time, O(1) space",
        "category": "linked_list",
    },
    {
        "round_type": "coding",
        "difficulty": "easy",
        "title": "Best Time to Buy and Sell Stock",
        "prompt": "Given an array prices where prices[i] is the price of a given stock on the ith day, find the maximum profit you can achieve from one transaction.",
        "description": "You want to maximize your profit by choosing a single day to buy and a single future day to sell. If no profit is possible, return 0.",
        "examples": [
            {"input": "prices = [7,1,5,3,6,4]", "output": "5", "explanation": "Buy on day 2 (price=1), sell on day 5 (price=6), profit = 6-1 = 5."},
            {"input": "prices = [7,6,4,3,1]", "output": "0", "explanation": "No transaction yields profit."},
        ],
        "constraints": ["1 <= prices.length <= 10^5", "0 <= prices[i] <= 10^4"],
        "hints": ["Track the minimum price seen so far.", "At each day, calculate potential profit if you sold today.", "Keep track of the maximum profit."],
        "optimal_complexity": "O(n) time, O(1) space",
        "category": "array",
    },
    # MEDIUM
    {
        "round_type": "coding",
        "difficulty": "medium",
        "title": "Valid Parentheses",
        "prompt": "Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.",
        "description": "An input string is valid if: Open brackets must be closed by the same type of brackets. Open brackets must be closed in the correct order. Every close bracket has a corresponding open bracket of the same type.",
        "examples": [
            {"input": 's = "()"', "output": "true", "explanation": "Simple matching pair"},
            {"input": 's = "()[]{}"', "output": "true", "explanation": "Multiple matching pairs"},
            {"input": 's = "(]"', "output": "false", "explanation": "Mismatched types"},
        ],
        "constraints": ["1 <= s.length <= 10^4", "s consists of parentheses only '()[]{}'"],
        "hints": ["Think about what data structure processes things in LIFO order.", "A stack can help track opening brackets.", "When you see a closing bracket, check if the top of stack matches."],
        "optimal_complexity": "O(n) time, O(n) space",
        "category": "stack",
    },
    {
        "round_type": "coding",
        "difficulty": "medium",
        "title": "Maximum Subarray",
        "prompt": "Given an integer array nums, find the subarray with the largest sum, and return its sum.",
        "description": "A subarray is a contiguous non-empty sequence of elements within an array.",
        "examples": [
            {"input": "nums = [-2,1,-3,4,-1,2,1,-5,4]", "output": "6", "explanation": "The subarray [4,-1,2,1] has the largest sum 6."},
            {"input": "nums = [1]", "output": "1", "explanation": "Single element"},
        ],
        "constraints": ["1 <= nums.length <= 10^5", "-10^4 <= nums[i] <= 10^4"],
        "hints": ["At each position, you have a choice: start fresh or extend the current subarray.", "Think about when extending becomes worse than starting over.", "Kadane's algorithm solves this in one pass."],
        "optimal_complexity": "O(n) time, O(1) space",
        "category": "dynamic_programming",
    },
    {
        "round_type": "coding",
        "difficulty": "medium",
        "title": "Group Anagrams",
        "prompt": "Given an array of strings strs, group the anagrams together. You can return the answer in any order.",
        "description": "An Anagram is a word formed by rearranging the letters of a different word, using all the original letters exactly once.",
        "examples": [
            {"input": 'strs = ["eat","tea","tan","ate","nat","bat"]', "output": '[["bat"],["nat","tan"],["ate","eat","tea"]]', "explanation": "Groups of anagrams."},
            {"input": 'strs = [""]', "output": '[[""]]', "explanation": "Empty string group."},
        ],
        "constraints": ["1 <= strs.length <= 10^4", "0 <= strs[i].length <= 100", "strs[i] consists of lowercase English letters."],
        "hints": ["What property do all anagrams share?", "If you sort the characters of each word, anagrams produce the same sorted string.", "Use the sorted string as a hash map key."],
        "optimal_complexity": "O(n * k log k) time where k is max string length",
        "category": "hash_map",
    },
    # HARD
    {
        "round_type": "coding",
        "difficulty": "hard",
        "title": "LRU Cache",
        "prompt": "Design a data structure that follows the constraints of a Least Recently Used (LRU) cache.",
        "description": "Implement the LRUCache class: LRUCache(int capacity) Initialize the cache with positive size capacity. int get(int key) Return the value of the key if it exists, otherwise return -1. void put(int key, int value) Update or insert the value. When the cache reaches capacity, evict the least recently used key.",
        "examples": [
            {"input": "LRUCache(2), put(1,1), put(2,2), get(1), put(3,3), get(2)", "output": "null,null,null,1,null,-1", "explanation": "After put(3,3), key 2 was evicted as LRU"},
        ],
        "constraints": ["1 <= capacity <= 3000", "0 <= key <= 10^4", "At most 2 * 10^5 operations"],
        "hints": ["You need O(1) for both get and put. What data structures give you that?", "Consider combining a hash map with a doubly linked list.", "The linked list maintains the usage order; the hash map gives O(1) lookup."],
        "optimal_complexity": "O(1) time for both get and put",
        "category": "design",
    },
    {
        "round_type": "coding",
        "difficulty": "hard",
        "title": "Merge K Sorted Lists",
        "prompt": "You are given an array of k linked-lists, each linked-list is sorted in ascending order. Merge all the linked-lists into one sorted linked-list and return it.",
        "description": "Merge k sorted linked lists into a single sorted linked list efficiently.",
        "examples": [
            {"input": "lists = [[1,4,5],[1,3,4],[2,6]]", "output": "[1,1,2,3,4,4,5,6]", "explanation": "All lists merged and sorted."},
            {"input": "lists = []", "output": "[]", "explanation": "Empty input."},
        ],
        "constraints": ["k == lists.length", "0 <= k <= 10^4", "0 <= lists[i].length <= 500", "-10^4 <= lists[i][j] <= 10^4"],
        "hints": ["What data structure efficiently gives you the minimum element?", "A min-heap (priority queue) can track the smallest head across all lists.", "Alternatively, use divide and conquer to merge pairs of lists."],
        "optimal_complexity": "O(N log k) time where N is total nodes",
        "category": "heap",
    },
]


async def seed_database():
    """Seed the database with coding questions and create indexes."""
    client = AsyncIOMotorClient(settings.MONGODB_URI)
    db = client[settings.MONGODB_DATABASE]

    # Clear and re-seed coding questions only
    await db.questions.delete_many({"round_type": "coding"})
    result = await db.questions.insert_many(CODING_QUESTIONS)
    print(f"Seeded {len(result.inserted_ids)} coding questions into MongoDB")

    # Create indexes
    await db.questions.create_index([("round_type", 1), ("difficulty", 1)])
    await db.sessions.create_index("session_id", unique=True)
    await db.sessions.create_index("email")
    await db.sessions.create_index("created_at")
    await db.evaluations.create_index("session_id")
    await db.evaluations.create_index("candidate_name")
    await db.evaluations.create_index([("candidate_name", 1), ("round_type", 1)])
    await db.evaluations.create_index([("session_id", 1), ("round_type", 1)])
    await db.users.create_index("email", unique=True)

    print("Database indexes created")
    client.close()


if __name__ == "__main__":
    asyncio.run(seed_database())
